/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alignment;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author sheik005
 */
public class ProteinAlignmentTest {
    
    public ProteinAlignmentTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }

    /**
     * Test of get_alignment method, of class ProteinAlignment.
     */
    @Test
    public void testGet_alignment() {
        System.out.println("get_alignment");
        String s1 = "MLPSWKAFKAHNILRILTRFQSTKIPDAVIGIDLGTTNSAVAIMEGKVPRIIENAEGSRTTPSVVAFTKDGERLVGEPAKRQSVINSENTLFATKRLIGRRFEDAEVQRDINQVPFKIVKHSNGDAWVEARNRTYSPAQIGGFILNKMKETAEAYLAKSVKNAVVTVPAYFNDAQRQATKDAGQIIGLNVLRVVNEPTAAALAYGLDKSEPKVIAVFDLGGGTFDISILDIDNGIFEVKSTNGDTHLGGEDFDIYLLQEIISHFKKETGIDLSNDRMAVQRIREAAEKAKIELSSTLSTEINLPFITADAAGPKHIRMPFSRVQLENITAPLIDRTVDPVKKALKDARITASDISDVLLVGGMSRMPKVADTVKKLFGKDASKAVNPDEAVALGAAIQAAVLSGEVTDVLLLDVTPLSLGIETLGGVFTKLIPRNSTIPNKKSQIFSTAASGQTSVEVKVFQGERELVKDNKLIGNFTLAGIPPAPKGIPQIEVTFDIDANGIINVSAKDLASHKDSSITVAGASGLSDTEIDRMVNEAERYKNQDRARRNAIETANKADQLANDTENSIKEFEGKLDKTDSQRLKDQISSLRELVSRIQAGDEVNDDDVGTKIDNLRTSSMKLFEQLYKNSDNPETKNGRENK*";
        String s2 = "MLKSGRLNFLKLNINSRLLYSTNPQLAKKVIGIDLGTTNSAVAYIRDSNDKKSATIIENDEGQRTTPSIVAFDVKSSPQNKDQMKTLVGMAAKRQNAINSENTFFATKRLIGRAFNDKEVQRDMAVMPYKIVKCESNGQAYLSTSNGLIQSPSQIASILLKYLKQTSEEYLGEKVNLAVITVPAYFNDSQRQATKDAGKLAGLNVLRVINEPTAAALSFGIDDKRNNGLIAVYDLGGGTFDISILDIEDGVFEVRATNGDTHLGGEDFDNVIVNYIIDTFIHENPEITREEITKNRETMQRLKDVSERAKIDLSHVKKTFIELPFVYKSKHLRVPMTEEELDNMTLSLINRTIPPVKQALKDADIEPEDIDEVILVGGMTRMPKIRSVVKDLFGKSPNSSVNPDETVALGAAIQGGILSGEIKNVLLLDVTPLTLGIETFGGAFSPLIPRNTTVPVKKTEIFSTGVDGQTGVDIKVFQGERGLVRNNKLIGDLKLTGITPLPKGIPQIYVTFDIDADGIINVSAAEKSSGKQQSITVIPNSGLSEEEIAKLIEEANANRAQDNLIRQRLELISKADIMISDTESLFKRYEKLISSEKEYSNIVEDIKALRQAIKNFKANENDMSIDVNGIKKATDALQGRALKLFQSATKNQQNQGK*";
        ProteinAlignment instance = new ProteinAlignment(-1.0,0.25,1000);
        AlignmentBlock result = instance.get_alignment(s1, s2);
        result.print();
    }

    /**
     * Test of get_similarity method, of class ProteinAlignment.
     */
    @Test
    public void testGet_similarity() {
        /*System.out.println("get_similarity");
        String s1 = "MVKPVIFAICLGVLLSKALSIPLRSFADIELIGSQKSLFPFLGGSAPYFSFPANYGIPTDIPEGCRLTQVQMIGRHGERYPTRSEAKDIFEVWYKISNYTGKYEGSLSFLNNGYEFFIPDESLLEMETTLQNSIDVLNPYTGEMNAKRHAREFLAKYGKLMENCTNFPIFTTNSKRIYDTAQYFAEALGDGFNISLQTLSENSSSGANTLAAKSSCPNWNSNANNDILMSYSRDYLENISDRLNDENKGLNLSRKDAAALFSWCAFELNAKGYSNICDIFSAAELIHYSYETDLTSFYQNGPGYKLIKSIGANLFNATVKLIRQSAHLDQKVWLSFTHDTDILNYLTTAGLIDDTRNLTTNHVPFRDHSYHRSWYIPQGARVYTEKFQCSNDSYVRYVVNDAVVPIESCSSGPGFSCEEGTFYEYAKDRLRGVSFYEDCDVSKVSKEKELTFYWDWNTTRYNASLVNQ*";
        String s2 = "MFKSVVYSILAASLANAGTIPLGKLADVDKIGTQKYIFPFLGGAGPYYSFPGDYGISRDLPEGCEMKQLQMVGRHGERYPTVSLAKTIKSTWYKLSNYTRQFNSSLSFLNDDYEFFIRDDDDLEMETTFANSDDVLNPYTGEMNAKRHARDFLAQYGYMVENQTSFAVFTSNSKRCHDTAQYFIDGLGDQFNITLQTVSEAESAGANTLSACNSCPAWDYDANDDIVNEYDTTYLDDIAKRLNKENKGLNLTSTDASTLFSWCAFEVNAKGYSDVCDIFTKDELVHYSYYQDLHTYYHEGPGYDIIKSVGSNLFNASVKLLKQSEIQDQKVWLSFTHDTDILNFLTTAGIIDDKNNLTAEYVPFMGNTFHRSWYVPQGARVYTEKFQCSNDTYVRYVINDAVVPIETCSTGPGFSCEINDFYDYAEKRVAGTDFLKVCNVSSVSNSTELTFYWDWNTTHYNASLLRQ*";
        ProteinAlignment instance = new ProteinAlignment();
        double result = instance.get_similarity(s1, s2);
        System.out.println("Similarity: " + result);*/
    }
    
}
